```{r knitsetup, echo=FALSE, results='hide', warning=FALSE, message=FALSE, cache=FALSE}
opts_knit$set(base.dir='./', fig.path='', out.format='md')
opts_chunk$set(prompt=TRUE, comment='', results='markup')
# See yihui.name/knitr/options for more Knitr options.
##### Put other setup R code here


# end setup chunk
```
# example 2
```{r}
library("bizdays");

# Cria o calendário
create.calendar(name="Brazil/ANBIMA", 
                holidays=holidaysANBIMA, 
                weekdays=c("saturday", "sunday") );
```

```{r}
data_compra <- as.Date("2017-08-04");
# data_vencim <- as.Date("2020-01-01");
data_vencim <- as.Date("2020-01-06");

datas <- seq.Date(from=data_compra, to=data_vencim, by="day");

tabela1 <- data.frame(datas);

tabela1$dia_semana <- weekdays(x=tabela1$datas);

tabela1$dia_util <- is.bizday(dates=tabela1$datas,  cal="Brazil/ANBIMA");
tabela1$dia_util <- as.integer(tabela1$dia_util);

# 04/08/2017 15:45
# Tesouro Prefixado 2020 (LTN)	01/01/2020	8,55	R$32,87	R$821,75

valor_compra <- 821.75;
tx_rend <- 8.55/100;

tabela1$valor_dia <- NA;
tabela1$valor_dia[1] <- valor_compra;

tx_admin <- 0.3/100;
tabela1$valor_admin <- NA;
tabela1$valor_admin [1] <- 0;

tabela1$id_dia_util <- NA;
tabela1$id_dia_util[1] <- 1;
jj <- 2;
for(ii in 2:nrow(tabela1) ){
  
  if(tabela1$dia_util[ii]==1){
    tabela1$valor_dia[ii] <- tabela1$valor_dia[ii-1] * (1 + tx_rend)^(1/252);
    
    tabela1$valor_admin[ii] <- tabela1$valor_dia[ii] * ( ((1+tx_admin)^(1/252)) - 1 );
    
    tabela1$id_dia_util[ii] <- jj;
    jj <- jj+1;
    
  } else{
    tabela1$valor_dia[ii] <- tabela1$valor_dia[ii-1];
    
    tabela1$valor_admin[ii] <- 0;
    
  }

}


```

```{r}

# R$ 2,47 + R$ 3,83 = 6.3
sum(tabela1$valor_admin[1:881]);

sum(tabela1$valor_admin[1:357]);

sum(tabela1$valor_admin[358:853]);

# https://www.euqueroinvestir.com/taxa-de-administracao-fundos-de-investimentos/

821.75 * ( ((1+tx_admin)^(252/252)) - 1 ); # 2.46525

821.75 * ( ((1+tx_admin)^(350/252)) - 1 ); # 3.425954

821.75 * ( ((1+tx_admin)^(126/252)) - 1 );
1.231702*3
# 602-252 = 350

# 891.4290
# 891.7193
# 892.0096
(0.3/100) * ( (876-365)/365 ) * ( (820.21+1000.00)/2 )

(0.3/100) * ( (876-365)/365 ) * ( (820.21+999.9926)/2 )

(0.5/100) * ( (747-365)/365 ) * ( (747.05+887.77)/2 )
```

```{r}
# Atualizado em: 07/08/2017 15:26
# Tesouro Prefixado 2020 (LTN)	01/01/2020	8,65	R$32,80	R$820,21

# Dias corridos entre a data de compra e a de vencimento:	876
# Dias corridos entre a data de compra e a de venda:	876
# Dias úteis entre a data de compra e a de vencimento:	602
# Dias úteis entre a data de compra e a de venda:	602
# Valor investido líquido:	R$ 820,21
# Rentabilidade bruta (a.a.):	8,51%
# Taxa de Negociação (0,0%):	R$ 0,00
# Taxa de administração na entrada:	R$ 2,46
# Valor investido bruto:	R$ 822,67
# Valor bruto do resgate:	R$ 1.000,00
# Valor da taxa de custódia do resgate:	R$ 6,55
# Valor da taxa de administração do resgate:	R$ 3,81
# Alíquota média de imposto de renda:	15,00%
# Imposto de renda:	R$ 25,41
# Valor líquido do resgate:	R$ 964,23
# Rentabilidade líquida após taxas e I.R. (a.a.):	6,87%


# http://carodinheiro.blogfolha.uol.com.br/2012/10/26/ltn-letras-tesouro-nacional-parte-3/

# http://nerdinvestidor.blogspot.com.br/2014/01/simulando-os-rendimentos-do-tesouro.html

```